---
title: "R For Data Science Introduction and ggplot2"
author: "Yuchin Stone Pan"
output: html_document 
---

First we'll install tidyverse.
```
install.packages("tidyverse")
```

This installs the packages tidyverse, ggplot2, tibble, tidyr, purrr, dyplyr, stringr, and forcats

We'll need 3 additional packages as well

```
install.packages(c("nycflights13", "gapminder", "Lahman"))
```

These packages provide data on airline flights, world development, and baseball.

# First Steps

Do cars with big engines use more fuel than cars with small engines? What does the relationship between engine size and fuel efficiency look like?

Start with the ggplot2 dataframe "mpg"

```
library(tidyverse)
mpg
```

For this one we want to look at **displ** which is the engine size in liters and **hwy** which is the car's fuel efficiency on the highway

```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
```

This plot shows a negative relationship between the two variables in this case.
Big engines use more fuel.


## Ggplot
ggplot()  creates a coordinate system you can add layers to.
  The first argument is the dataset to use in this case we used the mpg dataset
  This will be empty until we add layers to it.
    geom_point() adds a layer of points that creates a scatterplot
    ggplot comes with many different types of layers that can be worked together or seperately
    
    Each geom function within ggplot takes a mapping argument. This defines the # of variables in the dataset that are mapped to visual properties
    mappings are always tied to the aes(), and the x and y arguments of the aes()
      What is the x and y axis?
      
### Graphing template
```
ggplot (data = <DATA>) +
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
```

### Exercises
1. Run ggplot(data = mpg). What do you see?
2. How many rows are in mtcars? How many columns?
3. What does the drv variable describe? Read the help for ?mpg
4. Make a scatterplot of hwy versus cyl.
5. What happens if you make a scatterplot of class vs drv? Why is this not useful?

```
ggplot(data = mpg)
```
I see an empty graph.

```
mtcars
nrow(mtcars)
ncol(mtcars)
```
There are 32 rows and 11 columns in the mtcars dataset.

```
?mpg
```
drv is a categorical variable that is made up of 
  "f" = front-wheel drive
  "r" = rear-wheel drive
  "4" = 4 wheel drive
  
```
ggplot (data = mpg) +
  geom_point(mapping = aes(x = cyl, y = hwy))
```

```
ggplot (data = mpg) +
  geom_point(mapping = aes(x = class, y = drv))
```
This is not useful because this is mapping two categorical values against each other. It tells you nothing except for what class and drv a specific data point is. This doesn't show frequency or any kind of trend whatsoever.


## Aesthetic Mappings
We can add a third variable to our graphs called an aesthetic. An aesthetic is a visual property of the objects in the plot.
These can be shapes, sizes or colors of the points.

```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

Here we can see the outliers are 2 seaters. This probably means they are sports cars as they have large engines and due to their size get much better gas mileage.

### Other aesthetic options
Size of points
```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```
Transparency of points
```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```
Shape of points
```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```
ggplot will only use shapes for 6 of the options

We can also set these manually
```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy),color = "blue")
```


Another useful way to add categorical variables is through facets. Subplots that split out the data.

```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2)
```

```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ cyl)
```

```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)
```

## Geometric Objects
A geom is the geometric object that a plot uses to represent data.

```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

Every geom takes a mapping argument, but not every aesthetic works between them all. 

```
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```

This separates out each of the types of cars into their own line.
We can make this more clear by adding additional geoms

```
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

This particular one adds duplication in the code. We can fix this by adding the mappings in globally into the ggplot function itself.

```
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth()
```

If we place mappings in the grom function, ggplot2 will treat them as local mappings for the layer. It will use these mappings to extend or overwrite the global mappings for that layer only. This makes it possible to display different aesthetics in different layers

```
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth()
```

We can use this same logic to display different data for each layer. We overwrite the local variable with the smooth layer only.

```
ggplot(data = mpg, mapping = aes(x = displ,  y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth(
    data = filter(mpg, class == "subcompact"),
    se = FALSE
  )
```

## Bar Charts

Bar charts seem simple, but they are interesting because they reveal something subtle about plots.
Consider a basic bar chart, as drawn with geom_bar().
We'll use the diamonds dataset for this. This contains information about ~54,000 diamonds, including the price, carat, color, clarity and cut of each diamond. The charts show that more diamonds are available with high quality cuts than with low quality cuts.

```
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut))
```

Bar plots calculate new values for you to plot when in use. In this example "count".
  -Bar charts, histograms and frequency polygons bin your data and then plot bin counts, the number of points that fall into each bin.
  -Smoother fit a model to your data and then plot predictions from the model
  -Boxplots compute a robust summary of the distribution and display a specifically formatted box

The algorithm uised to calculate new values for a graph is called a stat, short for statistical transformation. 

Geoms and stats are interchangable i.e.

```
ggplot(data = diamonds) +
  stat_count(mapping = aes(x = cut))
```
This works because every stat has a default geom and vice versa. However there are 3 reasons you may want to use a stat specifically.

  1. You may want to override the base stat.
  2. You may want to override the default mapping from transformed variables to aesthetics.
    For example you want to show the same graph as before except by proportion rather than count
  3. You may want to draw greater attention to the statistical transformation in your code.
  
```
ggplot(data = diamonds) +
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```

### Position Adjustments

You can color a bar chart using either the same color aesthetic, or more usefully, fill.

```
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, color = cut))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = cut))
```

Color will fill in the line color, while fill will fill the entire bar with color.
This will automatically adjust when using a stack.

```
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity))
```
This stacking is done automically by the position adjustment specified in the position argument.

If you don't want stacking you can use, identity, dodge or fill.

  Position = "identity" will place each object exactly where it falls in context of the graph. This is not very useful for bars as they overlap. We can see the overlap by making them slightly transparent.
  
```
ggplot(
  data = diamonds,
  mapping = aes(x = cut, fill = clarity)
) +
  geom_bar(alpha = 1/5, position = "identity")

ggplot(
  data = diamonds,
  mapping = aes(x = cut, color = clarity)
) +
  geom_bar(fill = NA, position = "identity")
```

  Position = "fill" works like stacking, but makes every set of stacked bars the same height. This makes it easier to compare proportions between groups.
  
```
ggplot(data = diamonds) +
  geom_bar(
  mapping = aes(x = cut, fill = clarity),
  position = "fill"
)
```

  Position = "dodge" places overlapping objects directly beside one another. This makes it easier to compare individual values.
  
```
ggplot(data = diamonds) +
  geom_bar(
    mapping = aes(x = cut, fill = clarity),
    position = "dodge"
  )
```

We have one more that's not applied to bar charts, but to scatter. We can deal with the massing overlap of points on one mass by adding the jitter position.

This adds random small noise to each point so they are spread out.

```
ggplot(data = mpg) +
  geom_point(
  mapping = aes(x = displ, y = hwy),
  position = "jitter"
  )
```

This will make your chart less accurate on a small scale, but it improves it by making it much more revealing overall.

## Coordinate Systems
This is probably the most complicated part of ggplot2. The default coordinate system is the Cartesian coordinate system where the x and y position act independently to find the location of each point. 

  Coord_flip() switches the x- and y-axes. This is useful if you want horizontal boxplots or for long labels.
  
```
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot()
  
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot() +
  coord_flip()
```

  Coord_quickmap() sets the aspect ratio correctly for maps. This is very important if you're plotting spatial data. 
  
```
nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", color = "black")
  
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", color = "black") +
  coord_quickmap()
```

  Coord_polar() uses polar coordinates. This reveals an interesting connection between a bar chart and a Coxcomb chart,
  
```
bar <- ggplot(data = diamonds) +
  geom_bar(
    mapping = aes(x = cut, fill = cut),
    show.legend = FALSE,
    width = 1
  ) +
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()
```


  